-- Ödəniş şərtləri və ödəniş bağlantıları (bank hərəkəti <-> satış, çox-çoxa)
alter table deal add column payment_terms varchar(10) not null default 'POSTPAID';
alter table deal add column advance_percent numeric(5,2) not null default 0;
update deal set payment_terms = 'PREPAID', advance_percent = 100 where advance_invoice_no is not null or advance_amount is not null;

create table payment_allocation (
  id bigint generated by default as identity primary key,
  movement_id bigint not null references movement(id),
  deal_id bigint not null references deal(id),
  amount numeric(19,2) not null check (amount > 0),
  kind varchar(10) not null,
  file_id bigint,
  note varchar(1000),
  created_at timestamp not null
);
create index ix_alloc_movement on payment_allocation(movement_id);
create index ix_alloc_deal on payment_allocation(deal_id);

-- köhnə satış ödənişi (deal.payment_movement_id) -> bağlantı
insert into payment_allocation (movement_id, deal_id, amount, kind, file_id, note, created_at)
select m.id, d.id, least(coalesce(d.payment_amount, m.amount), m.amount),
       case when d.payment_terms = 'PREPAID' then 'ADVANCE' else 'FINAL' end, d.payment_file_id, null, current_timestamp
from deal d join movement m on m.id = d.payment_movement_id
where m.direction = 'IN' and coalesce(d.payment_amount, m.amount) > 0;

-- movement.deal_id olub bağlantısı olmayan mədaxillər
insert into payment_allocation (movement_id, deal_id, amount, kind, file_id, note, created_at)
select m.id, d.id, m.amount, case when d.payment_terms = 'PREPAID' then 'ADVANCE' else 'FINAL' end, m.file_id, null, current_timestamp
from movement m join deal d on d.id = m.deal_id
where m.direction = 'IN' and m.amount > 0 and not exists (select 1 from payment_allocation a where a.movement_id = m.id);

-- Köhnə sütunlar (deal.payment_date/payment_amount/payment_file_id/payment_movement_id, movement.deal_id) saxlanılır, lakin məntiqdə istifadə olunmur (deprecated).
