-- Bank/kart çıxarışları: hesaba bağlı fayl + dövr; hərəkət öz çıxarışına istinad edə bilər
create table account_statement (
  id bigint generated by default as identity primary key,
  account_id bigint not null references account(id),
  period_from date not null,
  period_to date not null,
  file_id bigint not null references stored_file(id),
  note varchar(1000),
  created_at timestamp not null default now()
);
create index ix_statement_account on account_statement(account_id);
alter table movement add column statement_id bigint references account_statement(id);
create index ix_movement_statement on movement(statement_id);
