-- Məhsulun default ödəniş şərti
alter table product add column default_payment_terms varchar(10);
alter table product add column default_advance_percent numeric(5,2);

-- Satışın ləğvi
alter table deal add column cancelled boolean not null default false;
alter table deal add column cancel_reason varchar(1000);
alter table deal add column cancelled_at timestamp;

-- Maaş cədvəli üzrə bank ödənişləri (vergi/NET sətirlərinin bank hərəkətlərinə bağlanması)
create table payroll_payment (
  id bigint generated by default as identity primary key,
  run_id bigint not null references payroll_run(id),
  code_key varchar(30) not null,
  employee_id bigint,
  amount numeric(19,2) not null check (amount > 0),
  movement_id bigint references movement(id),
  paid_date date,
  file_id bigint,
  note varchar(1000)
);
create index ix_payroll_payment_run on payroll_payment(run_id);
create index ix_payroll_payment_movement on payroll_payment(movement_id);

-- Maaş cədvəlinin sənədləri (bankın maaş ödəniş qəbzi, ödəniş tapşırıqları)
create table payroll_run_file (
  id bigint generated by default as identity primary key,
  run_id bigint not null references payroll_run(id),
  file_id bigint not null,
  title varchar(300),
  created_at timestamp not null default current_timestamp
);
create index ix_payroll_run_file_run on payroll_run_file(run_id);
