-- INNOTEX Sadə Uçot: əsas sxem (yalnız Flyway dəyişir)
create table app_user (
  id bigint generated by default as identity primary key,
  email varchar(200) not null unique,
  password_hash varchar(100) not null
);
create table session_token (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  created_at timestamp not null
);
create table settings (
  id bigint primary key,
  company_name varchar(300) not null default '',
  voen varchar(50) not null default '',
  address varchar(500) not null default '',
  director varchar(200) not null default '',
  bank varchar(300) not null default '',
  iban varchar(50) not null default '',
  bank_code varchar(50) not null default '',
  swift varchar(50) not null default '',
  phone varchar(100) not null default '',
  email varchar(200) not null default '',
  profit_tax_rate numeric(9,4) not null
);
create table payroll_rate (
  id bigint generated by default as identity primary key,
  valid_from varchar(7) not null,
  dsmf_limit numeric(19,4) not null,
  dsmf_emp_low numeric(19,4) not null,
  dsmf_emp_high numeric(19,4) not null,
  dsmf_er_low numeric(19,4) not null,
  dsmf_er_high numeric(19,4) not null,
  unemp_emp numeric(19,4) not null,
  unemp_er numeric(19,4) not null,
  med_limit numeric(19,4) not null,
  med_low numeric(19,4) not null,
  med_high numeric(19,4) not null,
  income_limit numeric(19,4) not null,
  income_exempt numeric(19,4) not null,
  income_low numeric(19,4) not null,
  income_high numeric(19,4) not null
);
create table work_calendar (
  period varchar(7) primary key,
  days integer not null
);
create table template (
  id bigint generated by default as identity primary key,
  code varchar(20) not null,
  title varchar(200) not null,
  html varchar(1000000) not null,
  is_default boolean not null default false
);
create table stored_file (
  id bigint generated by default as identity primary key,
  name varchar(300) not null,
  size_bytes bigint not null,
  stored_name varchar(100) not null
);
create table account (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  type varchar(20) not null,
  currency varchar(3) not null,
  opening_balance numeric(19,2) not null,
  opening_date date
);
create table expense (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  vendor varchar(300),
  category varchar(100) not null,
  description varchar(1000),
  amount numeric(19,2) not null,
  currency varchar(3) not null,
  rate numeric(19,6) not null,
  amount_azn numeric(19,2) not null,
  account_id bigint not null references account(id),
  deductible boolean not null,
  file_id bigint,
  note varchar(1000)
);
create table customer (
  id bigint generated by default as identity primary key,
  name varchar(300) not null,
  voen varchar(50),
  address varchar(500),
  director varchar(200),
  bank varchar(300),
  iban varchar(50),
  bank_code varchar(50),
  swift varchar(50),
  phone varchar(100),
  email varchar(200)
);
create table deal (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references customer(id),
  product varchar(300) not null,
  description varchar(2000),
  price numeric(19,2) not null,
  computers integer not null,
  stage varchar(20) not null,
  contract_no varchar(50),
  contract_date date,
  protocol_date date,
  advance_invoice_no varchar(50),
  advance_invoice_date date,
  advance_amount numeric(19,2),
  advance_file_id bigint,
  payment_date date,
  payment_amount numeric(19,2),
  payment_file_id bigint,
  payment_movement_id bigint,
  act_no varchar(50),
  act_date date,
  act_file_id bigint,
  invoice_no varchar(50),
  invoice_date date,
  invoice_amount numeric(19,2),
  invoice_file_id bigint,
  note varchar(2000),
  created_at timestamp not null
);
create table deal_event (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references deal(id),
  created_at timestamp not null,
  from_stage varchar(20),
  to_stage varchar(20) not null,
  note varchar(1000)
);
create table movement (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  account_id bigint not null references account(id),
  direction varchar(3) not null,
  amount numeric(19,2) not null,
  purpose varchar(30) not null,
  note varchar(1000),
  file_id bigint,
  deal_id bigint,
  expense_id bigint
);
create index ix_movement_account on movement(account_id);
create index ix_movement_date on movement(entry_date);
create table employee (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  job_title varchar(200),
  workplace varchar(10) not null,
  gross numeric(19,2) not null,
  active boolean not null
);
create table payroll_run (
  id bigint generated by default as identity primary key,
  period varchar(7) not null unique,
  status varchar(10) not null,
  norm_days integer not null
);
create table payroll_line (
  id bigint generated by default as identity primary key,
  run_id bigint not null references payroll_run(id),
  employee_id bigint,
  name varchar(200) not null,
  job_title varchar(200),
  workplace varchar(10) not null,
  gross numeric(19,2) not null,
  norm_days integer not null,
  worked_days integer not null,
  accrued numeric(19,2) not null,
  income numeric(19,2) not null,
  dsmf_emp numeric(19,2) not null,
  med_emp numeric(19,2) not null,
  unemp_emp numeric(19,2) not null,
  net numeric(19,2) not null,
  dsmf_er numeric(19,2) not null,
  med_er numeric(19,2) not null,
  unemp_er numeric(19,2) not null,
  employer_cost numeric(19,2) not null
);
create index ix_template_code on template(code);
create table deal_document (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references deal(id),
  code varchar(20) not null,
  template_id bigint,
  title varchar(300) not null,
  html varchar(1000000) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);
