-- Bank ödənişləri üçün büdcə kodları (istifadəçinin maaş Excel-indən), Ayarlardan dəyişdirilir
CREATE TABLE payment_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order  INT          NOT NULL,
    code_key    VARCHAR(30)  NOT NULL UNIQUE,
    title       VARCHAR(200) NOT NULL,
    budget_code VARCHAR(30),
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);
INSERT INTO payment_code (sort_order, code_key, title, budget_code, active) VALUES
 (1, 'INCOME_TAX', 'Gəlir vergisi (muzdlu iş)', '111111', TRUE),
 (2, 'DSMF_EMP', 'DSMF — işçidən tutulan', '121211', TRUE),
 (3, 'DSMF_ER', 'DSMF — işəgötürənin vəsaiti', '121111', TRUE),
 (4, 'MED_EMP', 'İcbari tibbi sığorta — işçidən tutulan', '124210', TRUE),
 (5, 'MED_ER', 'İcbari tibbi sığorta — işəgötürənin vəsaiti', '124110', TRUE),
 (6, 'UNEMP_EMP', 'İşsizlikdən sığorta — işçidən tutulan', '123200', TRUE),
 (7, 'UNEMP_ER', 'İşsizlikdən sığorta — işəgötürənin vəsaiti', '123100', TRUE),
 (8, 'NET', 'Əmək haqqı (işçilərin kartlarına)', NULL, TRUE);
