create table expense_item (
  id bigint generated by default as identity primary key,
  name varchar(200) not null unique,
  vendor varchar(300),
  category varchar(100),
  currency varchar(3) not null,
  default_amount numeric(19,2),
  account_id bigint references account(id),
  deductible boolean not null default true,
  recurrence varchar(10) not null,
  active boolean not null default true,
  note varchar(1000)
);
alter table expense add column item_id bigint references expense_item(id);
create index ix_expense_item on expense(item_id);

create table fx_rate (
  rate_date date not null,
  currency varchar(3) not null,
  rate numeric(18,4) not null,
  source varchar(20) not null default 'CBAR',
  fetched_at timestamp not null,
  primary key (rate_date, currency)
);
