create table product (
  id bigint generated by default as identity primary key,
  name varchar(300) not null unique,
  code varchar(100),
  unit varchar(50) not null default 'ədəd',
  default_price numeric(19,2),
  default_computers int,
  description varchar(2000),
  active boolean not null default true
);
alter table deal add column product_id bigint references product(id);
create index ix_deal_product on deal(product_id);
